server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

database:
  driverClass: org.h2.Driver
  user: sa
  url: jdbc:h2:tcp://localhost/~/test
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    charSet: UTF-8
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: validate # validates schema when service is started

  maxWaitForConnection: 1s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false